### ISSUE TITLE
we should respect `--api-server-address` regardless of whether we use kind

### ISSUE THREAD

**Issue by ilackarms** [solo-io/skv2#176]
currently cluster registration only allows user to override the apiserver address in the registrant's kubeconfig if the cluster is a `kind` cluster. this requirement is unncessary/invalid; there are many potential use cases in which the address of the apiserver is different between the user's machine and the management cluster.

we should remove the `kind` check here and always respect `api-server-address` flag:

https://github.com/solo-io/skv2/blob/3796bc6c1d912c9c896f60b11107bd42ff1732d5/pkg/multicluster/register/registrant.go#L642

**Comment by ashleywang1** [comment]
I'm gonna roll this in to a couple other changes I'm making. I ran into the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x37f1796]

goroutine 1 [running]:
github.com/solo-io/skv2/pkg/multicluster/register.RegistrationOptions.initialize(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff807, 0x14, 0x7ffeefbff7c0, 0xa, ...)
	/Users/ashwang/go/pkg/mod/github.com/solo-io/skv2@v0.13.5/pkg/multicluster/register/helpers.go:139 +0xa6
github.com/solo-io/skv2/pkg/multicluster/register.RegistrationOptions.RegisterProviderCluster(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff807, 0x14, 0x7ffeefbff7c0, 0xa, ...)
	/Users/ashwang/go/pkg/mod/github.com/solo-io/skv2@v0.13.5/pkg/multicluster/register/helpers.go:104 +0xcb
github.com/solo-io/skv2/pkg/multicluster/register.RegistrationOptions.RegisterCluster(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff807, 0x14, 0x7ffeefbff7c0, 0xa, ...)
	/Users/ashwang/go/pkg/mod/github.com/solo-io/skv2@v0.13.5/pkg/multicluster/register/helpers.go:92 +0x8c
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/federation/register.Register(0xc000bef500, 0x0, 0x0)
	/Users/ashwang/go/src/github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/federation/register/register.go:41 +0x48d
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/federation/register.RegisterCmd.func1(0xc000c86000, 0xc00005f200, 0x0, 0x8, 0x0, 0x0)
	/Users/ashwang/go/src/github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/federation/register/root.go:45 +0x3c
github.com/spf13/cobra.(*Command).execute(0xc000c86000, 0xc00005f180, 0x8, 0x8, 0x0, 0x0)
	/Users/ashwang/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0xb21
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c04000, 0xc000c86000, 0x0, 0x0)
	/Users/ashwang/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x70f
github.com/spf13/cobra.(*Command).Execute(0xc000c04000, 0x0, 0x0)
	/Users/ashwang/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887 +0x3b
main.main()
	/Users/ashwang/go/src/github.com/solo-io/gloo/projects/gloo/cli/cmd/main.go:11 +0x34
```
due to the following line:
https://github.com/solo-io/skv2/blob/3796bc6c1d912c9c896f60b11107bd42ff1732d5/pkg/multicluster/register/helpers.go#L139
